import fs from 'fs';
import path from 'path';
import readline from 'readline';

/**
 * Daily Log Insight Script
 * Analyzes the most recent NDJSON log file for operational patterns and issues.
 */

async function analyzeLogs() {
    const logsDir = path.join(process.cwd(), 'Logs');
    const files = fs.readdirSync(logsDir)
        .filter(f => f.endsWith('.log'))
        .map(f => ({
            name: f,
            time: fs.statSync(path.join(logsDir, f)).mtime.getTime()
        }))
        .sort((a, b) => b.time - a.time);

    if (files.length === 0) {
        console.log("No log files found in Logs directory.");
        return;
    }

    const latestFile = path.join(logsDir, files[0].name);
    console.log(`Analyzing: ${files[0].name}`);

    const stats = {
        totalLines: 0,
        levels: { AUDIT: 0, INFO: 0, WARN: 0, ERROR: 0 },
        events: {},
        crisisEvents: 0,
        overtimeCount: 0,
        totalWaitMinutes: 0,
        autopilotActions: 0,
        manualActions: 0,
        errors: []
    };

    const fileStream = fs.createReadStream(latestFile);
    const rl = readline.createInterface({
        input: fileStream,
        crlfDelay: Infinity
    });

    for await (const line of rl) {
        if (!line.trim()) continue;
        stats.totalLines++;

        try {
            const entry = JSON.parse(line);

            // Level aggregation
            stats.levels[entry.level] = (stats.levels[entry.level] || 0) + 1;
            if (entry.level === 'ERROR' || entry.level === 'WARN') {
                let reason = entry.event?.reason || entry.payload?.reason;

                // Enhanced reason for Load Shedding
                if (entry.event?.name === 'crisis.load_shed') {
                    reason = `Moved from ${entry.payload.from} to ${entry.payload.to} (${entry.payload.minutes_saved}m saved)`;
                }

                stats.errors.push({
                    ts: entry.ts,
                    event: entry.event?.name,
                    reason: reason || 'N/A',
                    module: entry.service?.module
                });
            }

            // Event aggregation
            const eventName = entry.event?.name;
            if (eventName) {
                stats.events[eventName] = (stats.events[eventName] || 0) + 1;

                if (eventName.includes('crisis')) stats.crisisEvents++;

                // Specific metrics
                if (entry.metrics?.is_overtime) stats.overtimeCount++;
                if (entry.payload?.delay_minutes) stats.totalWaitMinutes += entry.payload.delay_minutes;

                if (entry.metrics?.trigger === 'manual_balancer_shift') stats.manualActions++;
                if (entry.metrics?.source === 'crisis_autopilot') stats.autopilotActions++;
            }

        } catch (e) {
            // Probably not JSON or malformed
        }
    }

    // Generate Markdown Report
    const report = `# 📊 Daily Log Insights: ${files[0].name}

## 🚀 Operational Overview
- **Total Log Volume**: ${stats.totalLines} entries
- **Crisis Events**: ${stats.crisisEvents > 0 ? '🚨 ' + stats.crisisEvents : '✅ None'}
- **Overtime Frequency**: ${stats.overtimeCount} appointments
- **Total Reported Wait Time**: ${Math.round(stats.totalWaitMinutes / 60)} hours cumulative

## 🛠️ System Health (Levels)
| Level | Count |
|-------|-------|
| 🟢 AUDIT | ${stats.levels.AUDIT || 0} |
| 🔵 INFO  | ${stats.levels.INFO || 0} |
| 🟡 WARN  | ${stats.levels.WARN || 0} |
| 🔴 ERROR | ${stats.levels.ERROR || 0} |

## 🧩 Event Distribution (Top 5)
${Object.entries(stats.events)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5)
            .map(([name, count]) => `- **${name}**: ${count}`)
            .join('\n')}

## 🤖 Automation vs. Manual
- **Autopilot Moves**: ${stats.autopilotActions}
- **Manual Shifts**: ${stats.manualActions}

## ⚠️ Recent Issues/Warnings (Tail 5)
${stats.errors.slice(-5).map(e => `- [${e.ts}] **${e.event}** in *${e.module}*: ${e.reason}`).join('\n')}

---
*Generated by LogInsights Engine*
`;

    fs.writeFileSync(path.join(process.cwd(), 'DailyLogsWalkthrough.md'), report);
    console.log("Insight report generated: DailyLogsWalkthrough.md");
}

analyzeLogs().catch(console.error);
